[terminal.shell]
program = "/usr/local/bin/zellij"
args = [
  "-l",
  "welcome",
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 20

[font.normal]
family = "Intel One Mono"
style = "Regular"

[font.bold]
family = "Intel One Mono"
style = "Bold"

[font.bold_italic]
family = "Intel One Mono"
style = "Bold Italic"

[font.italic]
family = "Intel One Mono"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"
