[language-server.ruff]
command = "uvx ruff"
args = ["server"]

[language-server.ty]
command = "uvx ty"
args = ["server"]

[language-server.rust-analyzer.config]
checkOnSave = true

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
auto-format = true
formatter = { command = "sh", args = ["-c", "uvx ruff check --fix - | uvx ruff format -"] }
language-servers = [
  "ty",
  "ruff",
]
roots = ["pyproject.toml", ".git", ".venv", "venv"]

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }
