[*]
# Disable vision models
no-mmproj = true
# Load all layers to VRAM
n-gpu-layers = 999
# Flash Attention
flash-attn = on
# KV Cache
cache-type-k = q8_0
cache-type-v = q8_0
# Context
ctx-size = 65536
# Token Probability Distribution
temp = 1
top-p = 0.95
# Repeat Penalties
dry-multiplier = 0.8
dry-base = 1.75
dry-allowed-length = 3
dry-penalty-last-n = 1024
repeat-penalty = 1.05

[qwen-3.6-35b-a3b]
hf = unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_XL

[qwen-3.8-27b]
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL

[nemotron-3.5-30b-a3b]
hf = unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF:UD-Q4_K_XL
